using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GraphvizWrapper
{
    public enum Shape
    {
        None,
        Box,
        Polygon,
        Ellipse,
        Oval,
        Circle,
        Point,
        Egg,
        Triangle,
        PlainText,
        Plain,
        Diamond,
        Trapezium,
        Parallelogram,
        House,
        Pentagon,
        Hexagon,
        Septagon,
        Octagon,
        DoubleCircle,
        DoubleOctagon,
        TripleOctagon,
        InvTriangle,
        InvTrapezium,
        InvHouse,
        MDiamond,
        MSquare,
        MCircle,
        Rect,
        Rectangle,
        Square,
        Star,
        Underline,
        Cylinder,
        Note,
        Tab,
        Folder,
        Box3D,
        Component,
        Promoter,
        Cds,
        Terminator,
        Utr,
        Primersite,
        Restrictionite,
        FivePoverHang,
        ThreePoverHang,
        NoverHang,
        Assembly,
        Signature,
        Insulator,
        Ribosite,
        Rnastab,
        Proteasesite,
        Proteinstab,
        RPromoter,
        RArrow,
        LArrow,
        LPromoter,
        Record
    }
}